local parserVersion = "2019.02.11"
local parserName = "lua_wl_o365"

local O365 = nw.createParser(parserName, parserName .. ": " .. parserVersion)
-- this shows in the mouseover

nw.logDebug(parserName .. " " .. parserVersion)

local summary = {["parserName"] = parserName, ["parserVersion"] = parserVersion}

summary.parserDetails = [=[
marks Office365 traffic as whitelisted as well as the product name detected
looks for hostname and domains in the following keys 
    alias.host
    host.src
    host.dst
    fqdn

then marks them in the following keys
filter
with whitelist meta
    whitelist               - for global whitelisting
    o365                    - for office365 specifics
    'application name'      - for the application in office365 that leverages the hostname

the parser attempts to match both exact AND subdomain matches so for an entry that has both
a specific domain and overlapping *. wildcard subdomain you will potentially get 6 values written (3 for each match)
this can be changed by ordering the list from specific to substring and putting a break in teh loop to prevent after first match (specific first)

]=]

--[[
    VERSION
        2018.08.11.1  eric.partington@rsa.com  11.1.0.0-8987.3  UDM
        2018.10.10.2  eric.partington@rsa.com  updated to work with different lua import list
        
    OPTIONS
        none

    IMPLEMENTATION
        Relies on meta registered by other parsers.

    TODO
        none?
--]]
--local debugParser = require('debugParser')

local lookup_list = ({
["*-files.sharepoint.com"] = {"whitelist","office365","sharepoint"},
["*-myfiles.sharepoint.com"] = {"whitelist","office365","sharepoint"},
["*.aadrm.com"] = {"whitelist","office365","common"},
["*.acompli.net"] = {"whitelist","office365","common"},
["*.adhybridhealth.azure.com"] = {"whitelist","office365","common"},
["*.adl.windows.com"] = {"whitelist","office365","skype"},
["*.api.microsoftstream.com"] = {"whitelist","office365","common"},
["*.appex-rf.msn.com"] = {"whitelist","office365","common"},
["*.appex.bing.com"] = {"whitelist","office365","common"},
["*.aria.microsoft.com"] = {"whitelist","office365","common"},
["*.assets-yammer.com"] = {"whitelist","office365","common"},
["*.azureedge.net"] = {"whitelist","office365","common"},
["*.azurerms.com"] = {"whitelist","office365","common"},
["*.blob.core.windows.net"] = {"whitelist","office365","common"},
["*.broadcast.skype.com"] = {"whitelist","office365","skype"},
["*.cdn.office.net"] = {"whitelist","office365","common"},
["*.cloudapp.net"] = {"whitelist","office365","common"},
["*.entrust.net"] = {"whitelist","office365","common"},
["*.events.data.microsoft.com"] = {"whitelist","office365","common"},
["*.geotrust.com"] = {"whitelist","office365","common"},
["*.helpshift.com"] = {"whitelist","office365","common"},
["*.hockeyapp.net"] = {"whitelist","office365","common"},
["*.itunes.apple.com"] = {"whitelist","office365","common"},
["*.keydelivery.mediaservices.windows.net"] = {"whitelist","office365","common"},
["*.keydelivery.mediaservices.windows.net"] = {"whitelist","office365","skype"},
["*.localytics.com"] = {"whitelist","office365","common"},
["*.log.optimizely.com"] = {"whitelist","office365","sharepoint"},
["*.loki.delve.office.com"] = {"whitelist","office365","common"},
["*.lync.com"] = {"whitelist","office365","skype"},
["*.mail.protection.outlook.com"] = {"whitelist","office365","exchange"},
["*.manage.microsoft.com"] = {"whitelist","office365","common"},
["*.manage.office.com"] = {"whitelist","office365","common"},
["*.media.azure.net"] = {"whitelist","office365","common"},
["*.microsoft.com"] = {"whitelist","office365","common"},
["*.microsoftonline-p.com"] = {"whitelist","office365","common"},
["*.microsoftonline-p.net"] = {"whitelist","office365","common"},
["*.microsoftonline.com"] = {"whitelist","office365","common"},
["*.msappproxy.net"] = {"whitelist","office365","common"},
["*.msauth.net"] = {"whitelist","office365","common"},
["*.msauthimages.net"] = {"whitelist","office365","common"},
["*.msecnd.net"] = {"whitelist","office365","common"},
["*.msecnd.net"] = {"whitelist","office365","skype"},
["*.msedge.net"] = {"whitelist","office365","skype"},
["*.msftauth.net"] = {"whitelist","office365","common"},
["*.msftauthimages.net"] = {"whitelist","office365","common"},
["*.msocdn.com"] = {"whitelist","office365","common"},
["*.mstea.ms"] = {"whitelist","office365","skype"},
["*.notification.api.microsoftstream.com"] = {"whitelist","office365","common"},
["*.o365weve.com"] = {"whitelist","office365","common"},
["*.office.com"] = {"whitelist","office365","common"},
["*.office.net"] = {"whitelist","office365","common"},
["*.office365.com"] = {"whitelist","office365","common"},
["*.officeconfig.msocdn.com"] = {"whitelist","office365","common"},
["*.omniroot.com"] = {"whitelist","office365","common"},
["*.onenote.com"] = {"whitelist","office365","common"},
["*.onmicrosoft.com"] = {"whitelist","office365","common"},
["*.outlook.com"] = {"whitelist","office365","exchange"},
["*.outlook.office.com"] = {"whitelist","office365","exchange"},
["*.outlookmobile.com"] = {"whitelist","office365","common"},
["*.outlookmobile.us"] = {"whitelist","office365","common"},
["*.phonefactor.net"] = {"whitelist","office365","common"},
["*.portal.cloudappsecurity.com"] = {"whitelist","office365","common"},
["*.protection.office.com"] = {"whitelist","office365","common"},
["*.protection.outlook.com"] = {"whitelist","office365","exchange"},
["*.public-trust.com"] = {"whitelist","office365","common"},
["*.queue.core.windows.net"] = {"whitelist","office365","common"},
["*.search.production.apac.trafficmanager.net"] = {"whitelist","office365","sharepoint"},
["*.search.production.emea.trafficmanager.net"] = {"whitelist","office365","sharepoint"},
["*.search.production.us.trafficmanager.net"] = {"whitelist","office365","sharepoint"},
["*.secure.skypeassets.com"] = {"whitelist","office365","skype"},
["*.servicebus.windows.net"] = {"whitelist","office365","common"},
["*.sfbassets.com"] = {"whitelist","office365","skype"},
["*.sharepoint.com"] = {"whitelist","office365","sharepoint"},
["*.sharepointonline.com"] = {"whitelist","office365","common"},
["*.sharepointonline.com"] = {"whitelist","office365","sharepoint"},
["*.skype.com"] = {"whitelist","office365","skype"},
["*.skypeforbusiness.com"] = {"whitelist","office365","skype"},
["*.staffhub.office.com"] = {"whitelist","office365","common"},
["*.store.core.windows.net"] = {"whitelist","office365","exchange"},
["*.streaming.mediaservices.windows.net"] = {"whitelist","office365","common"},
["*.streaming.mediaservices.windows.net"] = {"whitelist","office365","skype"},
["*.svc.ms"] = {"whitelist","office365","sharepoint"},
["*.symcb.com"] = {"whitelist","office365","common"},
["*.symcd.com"] = {"whitelist","office365","common"},
["*.table.core.windows.net"] = {"whitelist","office365","common"},
["*.teams.microsoft.com"] = {"whitelist","office365","skype"},
["*.tenor.com"] = {"whitelist","office365","skype"},
["*.urlp.sfbassets.com"] = {"whitelist","office365","skype"},
["*.users.storage.live.com"] = {"whitelist","office365","skype"},
["*.verisign.com"] = {"whitelist","office365","common"},
["*.verisign.net"] = {"whitelist","office365","common"},
["*.windows.net"] = {"whitelist","office365","common"},
["*.yammer.com"] = {"whitelist","office365","common"},
["*.yammerusercontent.com"] = {"whitelist","office365","common"},
["*broadcast.officeapps.live.com"] = {"whitelist","office365","common"},
["*cdn.onenote.net"] = {"whitelist","office365","common"},
["*excel.officeapps.live.com"] = {"whitelist","office365","common"},
["*onenote.officeapps.live.com"] = {"whitelist","office365","common"},
["*powerpoint-podsws.officeapps.live.com"] = {"whitelist","office365","common"},
["*powerpoint.officeapps.live.com"] = {"whitelist","office365","common"},
["*rtc.officeapps.live.com"] = {"whitelist","office365","common"},
["*shared.officeapps.live.com"] = {"whitelist","office365","common"},
["*view.officeapps.live.com"] = {"whitelist","office365","common"},
["*visio.officeapps.live.com"] = {"whitelist","office365","common"},
["*word-edit.officeapps.live.com"] = {"whitelist","office365","common"},
["*word-view.officeapps.live.com"] = {"whitelist","office365","common"},
["a.wunderlist.com"] = {"whitelist","office365","common"},
["account.activedirectory.windowsazure.com"] = {"whitelist","office365","common"},
["account.live.com"] = {"whitelist","office365","common"},
["account.office.net"] = {"whitelist","office365","common"},
["accounts.accesscontrol.windows.net"] = {"whitelist","office365","common"},
["accounts.google.com"] = {"whitelist","office365","common"},
["acompli.helpshift.com"] = {"whitelist","office365","common"},
["activation.sls.microsoft.com"] = {"whitelist","office365","common"},
["ad.atdmt.com"] = {"whitelist","office365","common"},
["admin.microsoft.com"] = {"whitelist","office365","common"},
["admin.onedrive.com"] = {"whitelist","office365","sharepoint"},
["adminwebservice.microsoftonline.com"] = {"whitelist","office365","common"},
["aia.entrust.net"] = {"whitelist","office365","common"},
["ajax.aspnetcdn.com"] = {"whitelist","office365","common"},
["ajax.aspnetcdn.com"] = {"whitelist","office365","skype"},
["ajax.microsoft.com"] = {"whitelist","office365","common"},
["aka.ms"] = {"whitelist","office365","skype"},
["amp.azure.net"] = {"whitelist","office365","common"},
["amp.azure.net"] = {"whitelist","office365","skype"},
["amsglob0cdnstream11.azureedge.net"] = {"whitelist","office365","common"},
["amsglob0cdnstream12.azureedge.net"] = {"whitelist","office365","common"},
["analytics.localytics.com"] = {"whitelist","office365","common"},
["apc.delve.office.com"] = {"whitelist","office365","common"},
["api.diagnostics.office.com"] = {"whitelist","office365","common"},
["api.dropboxapi.com"] = {"whitelist","office365","common"},
["api.informationprotection.azure.com"] = {"whitelist","office365","common"},
["api.localytics.com"] = {"whitelist","office365","common"},
["api.login.microsoftonline.com"] = {"whitelist","office365","common"},
["api.login.yahoo.com"] = {"whitelist","office365","common"},
["api.meetup.com"] = {"whitelist","office365","common"},
["api.microsoftstream.com"] = {"whitelist","office365","common"},
["api.office.com"] = {"whitelist","office365","common"},
["api.passwordreset.microsoftonline.com"] = {"whitelist","office365","common"},
["apis.live.net"] = {"whitelist","office365","common"},
["app.adjust.com"] = {"whitelist","office365","common"},
["app.box.com"] = {"whitelist","office365","common"},
["apps.identrust.com"] = {"whitelist","office365","common"},
["appsforoffice.microsoft.com"] = {"whitelist","office365","common"},
["asl.configure.office.com"] = {"whitelist","office365","exchange"},
["assets.onestore.ms"] = {"whitelist","office365","common"},
["attachments.office.net"] = {"whitelist","office365","exchange"},
["aus.delve.office.com"] = {"whitelist","office365","common"},
["auth.gfx.ms"] = {"whitelist","office365","common"},
["autologon.microsoftazuread-sso.com"] = {"whitelist","office365","common"},
["az416426.vo.msecnd.net"] = {"whitelist","office365","common"},
["az826701.vo.msecnd.net"] = {"whitelist","office365","common"},
["becws.microsoftonline.com"] = {"whitelist","office365","common"},
["bit.ly"] = {"whitelist","office365","common"},
["broadcast.skype.com"] = {"whitelist","office365","skype"},
["by.uservoice.com"] = {"whitelist","office365","common"},
["c.bing.com"] = {"whitelist","office365","common"},
["c.bing.net"] = {"whitelist","office365","common"},
["c.live.com"] = {"whitelist","office365","common"},
["c1.microsoft.com"] = {"whitelist","office365","common"},
["cacert.a.omniroot.com"] = {"whitelist","office365","common"},
["cacert.omniroot.com"] = {"whitelist","office365","common"},
["cacerts.digicert.com"] = {"whitelist","office365","common"},
["can.delve.office.com"] = {"whitelist","office365","common"},
["ccs.login.microsoftonline.com"] = {"whitelist","office365","common"},
["cdn.odc.officeapps.live.com"] = {"whitelist","office365","common"},
["cdn.optimizely.com"] = {"whitelist","office365","common"},
["cdn.sharepointonline.com"] = {"whitelist","office365","sharepoint"},
["cdp1.public-trust.com"] = {"whitelist","office365","common"},
["cert.int-x3.letsencrypt.org"] = {"whitelist","office365","common"},
["cl2.apple.com"] = {"whitelist","office365","common"},
["click.email.microsoftonline.com"] = {"whitelist","office365","sharepoint"},
["client.hip.live.com"] = {"whitelist","office365","common"},
["clientconfig.microsoftonline-p.net"] = {"whitelist","office365","common"},
["companymanager.microsoftonline.com"] = {"whitelist","office365","common"},
["compass-ssl.microsoft.com"] = {"whitelist","office365","skype"},
["config.office.com"] = {"whitelist","office365","common"},
["connect.facebook.net"] = {"whitelist","office365","common"},
["contentstorage.osi.office.net"] = {"whitelist","office365","common"},
["crl.entrust.net"] = {"whitelist","office365","common"},
["crl.globalsign.com"] = {"whitelist","office365","common"},
["crl.globalsign.net"] = {"whitelist","office365","common"},
["crl.identrust.com"] = {"whitelist","office365","common"},
["crl.microsoft.com"] = {"whitelist","office365","common"},
["crl3.digicert.com"] = {"whitelist","office365","common"},
["crl4.digicert.com"] = {"whitelist","office365","common"},
["cus-000.tasks.osi.office.net"] = {"whitelist","office365","common"},
["d.docs.live.net"] = {"whitelist","office365","common"},
["data.flurry.com"] = {"whitelist","office365","common"},
["dc.applicationinsights.microsoft.com"] = {"whitelist","office365","common"},
["dc.services.visualstudio.com"] = {"whitelist","office365","common"},
["delve-gcc.office.com"] = {"whitelist","office365","common"},
["delve.office.com"] = {"whitelist","office365","common"},
["device.login.microsoftonline.com"] = {"whitelist","office365","common"},
["dgps.support.microsoft.com"] = {"whitelist","office365","common"},
["directory.services.live.com"] = {"whitelist","office365","common"},
["docs.live.net"] = {"whitelist","office365","common"},
["docs.microsoft.com"] = {"whitelist","office365","common"},
["domains.live.com"] = {"whitelist","office365","exchange"},
["ea-000.forms.osi.office.net"] = {"whitelist","office365","common"},
["ea-000.tasks.osi.office.net"] = {"whitelist","office365","common"},
["ecn.dev.virtualearth.net"] = {"whitelist","office365","common"},
["en-us.appex-rf.msn.com"] = {"whitelist","office365","common"},
["enterpriseregistration.windows.net"] = {"whitelist","office365","common"},
["eur.delve.office.com"] = {"whitelist","office365","common"},
["eus-www.sway-cdn.com"] = {"whitelist","office365","common"},
["eus-www.sway-extensions.com"] = {"whitelist","office365","common"},
["eus-zzz.tasks.osi.office.net"] = {"whitelist","office365","common"},
["eus2-000.forms.osi.office.net"] = {"whitelist","office365","common"},
["evintl-aia.verisign.com"] = {"whitelist","office365","common"},
["evintl-crl.verisign.com"] = {"whitelist","office365","common"},
["evintl-ocsp.verisign.com"] = {"whitelist","office365","common"},
["evsecure-aia.verisign.com"] = {"whitelist","office365","common"},
["evsecure-crl.verisign.com"] = {"whitelist","office365","common"},
["evsecure-ocsp.verisign.com"] = {"whitelist","office365","common"},
["excelbingmap.firstpartyapps.oaspapps.com"] = {"whitelist","office365","common"},
["excelcs.officeapps.live.com"] = {"whitelist","office365","common"},
["firstpartyapps.oaspapps.com"] = {"whitelist","office365","common"},
["foodanddrink.services.appex.bing.com"] = {"whitelist","office365","common"},
["forms.microsoft.com"] = {"whitelist","office365","common"},
["forms.office.com"] = {"whitelist","office365","common"},
["g.live.com"] = {"whitelist","office365","sharepoint"},
["gbr.delve.office.com"] = {"whitelist","office365","common"},
["go.microsoft.com"] = {"whitelist","office365","common"},
["graph.facebook.com"] = {"whitelist","office365","common"},
["graph.microsoft.com"] = {"whitelist","office365","common"},
["graph.windows.net"] = {"whitelist","office365","common"},
["hip.microsoftonline-p.net"] = {"whitelist","office365","common"},
["hipservice.microsoftonline.com"] = {"whitelist","office365","common"},
["home.office.com"] = {"whitelist","office365","common"},
["ind.delve.office.com"] = {"whitelist","office365","common"},
["informationprotection.hosting.portal.azure.net"] = {"whitelist","office365","common"},
["insertmedia.bing.office.net"] = {"whitelist","office365","common"},
["isrg.trustid.ocsp.identrust.com"] = {"whitelist","office365","common"},
["jpn.delve.office.com"] = {"whitelist","office365","common"},
["kor.delve.office.com"] = {"whitelist","office365","common"},
["lam.delve.office.com"] = {"whitelist","office365","common"},
["login-us.microsoftonline.com"] = {"whitelist","office365","common"},
["login.live.com"] = {"whitelist","office365","common"},
["login.microsoft.com"] = {"whitelist","office365","common"},
["login.microsoftonline-p.com"] = {"whitelist","office365","common"},
["login.microsoftonline.com"] = {"whitelist","office365","common"},
["login.windows-ppe.net"] = {"whitelist","office365","common"},
["login.windows.net"] = {"whitelist","office365","common"},
["logincert.microsoftonline.com"] = {"whitelist","office365","common"},
["loginex.microsoftonline.com"] = {"whitelist","office365","common"},
["loki.delve-gcc.office.com"] = {"whitelist","office365","common"},
["loki.delve.office.com"] = {"whitelist","office365","common"},
["lpcres.delve.office.com"] = {"whitelist","office365","common"},
["m.facebook.com"] = {"whitelist","office365","common"},
["mail.google.com"] = {"whitelist","office365","common"},
["manage.office.com"] = {"whitelist","office365","common"},
["management.azure.com"] = {"whitelist","office365","common"},
["mem.gfx.ms"] = {"whitelist","office365","common"},
["mlccdn.blob.core.windows.net"] = {"whitelist","office365","skype"},
["mlccdnprod.azureedge.net"] = {"whitelist","office365","skype"},
["mrodevicemgr.officeapps.live.com"] = {"whitelist","office365","common"},
["ms.tific.com"] = {"whitelist","office365","common"},
["mscrl.microsoft.com"] = {"whitelist","office365","common"},
["msdn.microsoft.com"] = {"whitelist","office365","common"},
["mshrcstorageprod.blob.core.windows.net"] = {"whitelist","office365","exchange"},
["nam.delve.office.com"] = {"whitelist","office365","common"},
["neu-000.forms.osi.office.net"] = {"whitelist","office365","common"},
["neu-000.tasks.osi.office.net"] = {"whitelist","office365","common"},
["nexus.microsoftonline-p.com"] = {"whitelist","office365","common"},
["nexus.officeapps.live.com"] = {"whitelist","office365","common"},
["nexusrules.officeapps.live.com"] = {"whitelist","office365","common"},
["nps.onyx.azure.net"] = {"whitelist","office365","common"},
["o15.officeredir.microsoft.com"] = {"whitelist","office365","common"},
["ocos-office365-s2s.msedge.net"] = {"whitelist","office365","common"},
["ocsa.officeapps.live.com"] = {"whitelist","office365","common"},
["ocsp.digicert.com"] = {"whitelist","office365","common"},
["ocsp.entrust.net"] = {"whitelist","office365","common"},
["ocsp.globalsign.com"] = {"whitelist","office365","common"},
["ocsp.int-x3.letsencrypt.org"] = {"whitelist","office365","common"},
["ocsp.msocsp.com"] = {"whitelist","office365","common"},
["ocsp.omniroot.com"] = {"whitelist","office365","common"},
["ocsp2.globalsign.com"] = {"whitelist","office365","common"},
["ocspx.digicert.com"] = {"whitelist","office365","common"},
["ocsredir.officeapps.live.com"] = {"whitelist","office365","common"},
["ocws.officeapps.live.com"] = {"whitelist","office365","common"},
["odc.officeapps.live.com"] = {"whitelist","office365","common"},
["odcsm.officeapps.live.com"] = {"whitelist","office365","common"},
["office.live.com"] = {"whitelist","office365","common"},
["office.microsoft.com"] = {"whitelist","office365","common"},
["office15client.microsoft.com"] = {"whitelist","office365","common"},
["office365servicehealthcommunications.cloudapp.net"] = {"whitelist","office365","common"},
["officeapps.live.com"] = {"whitelist","office365","common"},
["officecdn.microsoft.com"] = {"whitelist","office365","common"},
["officecdn.microsoft.com.edgesuite.net"] = {"whitelist","office365","common"},
["officeclient.microsoft.com"] = {"whitelist","office365","common"},
["officeclient.microsoft.com"] = {"whitelist","office365","sharepoint"},
["officeimg.vo.msecnd.net"] = {"whitelist","office365","common"},
["officepreviewredir.microsoft.com"] = {"whitelist","office365","common"},
["officeredir.microsoft.com"] = {"whitelist","office365","common"},
["officespeech.platform.bing.com"] = {"whitelist","office365","common"},
["ols.officeapps.live.com"] = {"whitelist","office365","common"},
["omextemplates.content.office.net"] = {"whitelist","office365","common"},
["oneclient.sfx.ms"] = {"whitelist","office365","sharepoint"},
["outlook.office.com"] = {"whitelist","office365","exchange"},
["outlook.office365.com"] = {"whitelist","office365","exchange"},
["outlook.uservoice.com"] = {"whitelist","office365","common"},
["p100-sandbox.itunes.apple.com"] = {"whitelist","office365","common"},
["partnerservices.getmicrosoftkey.com"] = {"whitelist","office365","common"},
["passwordreset.microsoftonline.com"] = {"whitelist","office365","common"},
["peoplegraph.firstpartyapps.oaspapps.com"] = {"whitelist","office365","common"},
["platform.linkedin.com"] = {"whitelist","office365","common"},
["play.google.com"] = {"whitelist","office365","common"},
["policykeyservice.dc.ad.msft.net"] = {"whitelist","office365","common"},
["portal.microsoftonline.com"] = {"whitelist","office365","common"},
["portal.office.com"] = {"whitelist","office365","common"},
["pptcs.officeapps.live.com"] = {"whitelist","office365","common"},
["privatecdn.sharepointonline.com"] = {"whitelist","office365","sharepoint"},
["prod.firstpartyapps.oaspapps.com.akadns.net"] = {"whitelist","office365","common"},
["prod.msocdn.com"] = {"whitelist","office365","common"},
["prod.msocdn.com"] = {"whitelist","office365","sharepoint"},
["products.office.com"] = {"whitelist","office365","common"},
["protection.office.com"] = {"whitelist","office365","common"},
["provisioningapi.microsoftonline.com"] = {"whitelist","office365","common"},
["publiccdn.sharepointonline.com"] = {"whitelist","office365","sharepoint"},
["quicktips.skypeforbusiness.com"] = {"whitelist","office365","skype"},
["r.office.microsoft.com"] = {"whitelist","office365","common"},
["r1.res.office365.com"] = {"whitelist","office365","common"},
["r1.res.office365.com"] = {"whitelist","office365","exchange"},
["r3.res.office365.com"] = {"whitelist","office365","exchange"},
["r3.res.outlook.com"] = {"whitelist","office365","common"},
["r4.res.office365.com"] = {"whitelist","office365","common"},
["r4.res.office365.com"] = {"whitelist","office365","exchange"},
["res.delve.office.com"] = {"whitelist","office365","common"},
["rink.hockeyapp.net"] = {"whitelist","office365","common"},
["roaming.officeapps.live.com"] = {"whitelist","office365","common"},
["s.ytimg.com"] = {"whitelist","office365","common"},
["s0.assets-yammer.com"] = {"whitelist","office365","common"},
["s1.symcb.com"] = {"whitelist","office365","common"},
["s2.symcb.com"] = {"whitelist","office365","common"},
["sa.symcb.com"] = {"whitelist","office365","common"},
["sas.office.microsoft.com"] = {"whitelist","office365","common"},
["scsinstrument-ss-us.trafficmanager.net"] = {"whitelist","office365","skype"},
["scsquery-ss-asia.trafficmanager.net"] = {"whitelist","office365","skype"},
["scsquery-ss-eu.trafficmanager.net"] = {"whitelist","office365","skype"},
["scsquery-ss-us.trafficmanager.net"] = {"whitelist","office365","skype"},
["sd.symcb.com"] = {"whitelist","office365","common"},
["sdk.hockeyapp.net"] = {"whitelist","office365","common"},
["sea-000.tasks.osi.office.net"] = {"whitelist","office365","common"},
["secure.aadcdn.microsoftonline-p.com"] = {"whitelist","office365","common"},
["secure.globalsign.com"] = {"whitelist","office365","common"},
["secure.meetup.com"] = {"whitelist","office365","common"},
["securescore.office.com"] = {"whitelist","office365","common"},
["shellprod.msocdn.com"] = {"whitelist","office365","common"},
["signup.live.com"] = {"whitelist","office365","common"},
["signup.microsoft.com"] = {"whitelist","office365","common"},
["skydrive.wns.windows.com"] = {"whitelist","office365","sharepoint"},
["skypemaprdsitus.trafficmanager.net"] = {"whitelist","office365","skype"},
["smtp.office365.com"] = {"whitelist","office365","exchange"},
["social.yahooapis.com"] = {"whitelist","office365","common"},
["spoprod-a.akamaihd.net"] = {"whitelist","office365","common"},
["spoprod-a.akamaihd.net"] = {"whitelist","office365","sharepoint"},
["sr.symcb.com"] = {"whitelist","office365","common"},
["sr.symcd.com"] = {"whitelist","office365","common"},
["ssw.live.com"] = {"whitelist","office365","sharepoint"},
["staffhub.ms"] = {"whitelist","office365","common"},
["staffhub.office.com"] = {"whitelist","office365","common"},
["staffhub.uservoice.com"] = {"whitelist","office365","common"},
["staffhubweb.azureedge.net"] = {"whitelist","office365","common"},
["static.sharepointonline.com"] = {"whitelist","office365","sharepoint"},
["storage.live.com"] = {"whitelist","office365","sharepoint"},
["store.office.com"] = {"whitelist","office365","common"},
["su.symcb.com"] = {"whitelist","office365","common"},
["su.symcd.com"] = {"whitelist","office365","common"},
["suite.office.net"] = {"whitelist","office365","common"},
["support.content.office.net"] = {"whitelist","office365","common"},
["support.microsoft.com"] = {"whitelist","office365","common"},
["support.office.com"] = {"whitelist","office365","common"},
["sway.com"] = {"whitelist","office365","common"},
["sway.office.com"] = {"whitelist","office365","common"},
["tasks.office.com"] = {"whitelist","office365","common"},
["tds.configure.office.com"] = {"whitelist","office365","exchange"},
["teams.microsoft.com"] = {"whitelist","office365","skype"},
["technet.microsoft.com"] = {"whitelist","office365","common"},
["telemetryservice.firstpartyapps.oaspapps.com"] = {"whitelist","office365","common"},
["templates.office.com"] = {"whitelist","office365","common"},
["templateservice.office.com"] = {"whitelist","office365","common"},
["testconnectivity.microsoft.com"] = {"whitelist","office365","common"},
["tse1.mm.bing.net"] = {"whitelist","office365","common"},
["uci.officeapps.live.com"] = {"whitelist","office365","common"},
["vassg142.crl.omniroot.com"] = {"whitelist","office365","common"},
["vassg142.ocsp.omniroot.com"] = {"whitelist","office365","common"},
["video.osi.office.net"] = {"whitelist","office365","common"},
["videocontent.osi.office.net"] = {"whitelist","office365","common"},
["videoplayercdn.osi.office.net"] = {"whitelist","office365","common"},
["videoplayercdn.osi.office.net"] = {"whitelist","office365","skype"},
["view.atdmt.com"] = {"whitelist","office365","common"},
["vortex.data.microsoft.com"] = {"whitelist","office365","common"},
["watson.microsoft.com"] = {"whitelist","office365","common"},
["watson.telemetry.microsoft.com"] = {"whitelist","office365","common"},
["watson.telemetry.microsoft.com"] = {"whitelist","office365","sharepoint"},
["weather.tile.appex.bing.com"] = {"whitelist","office365","common"},
["web.localytics.com"] = {"whitelist","office365","common"},
["web.microsoftstream.com"] = {"whitelist","office365","common"},
["webanalytics.localytics.com"] = {"whitelist","office365","common"},
["webshell.suite.office.com"] = {"whitelist","office365","common"},
["weu-000.forms.osi.office.net"] = {"whitelist","office365","common"},
["weu-000.tasks.osi.office.net"] = {"whitelist","office365","common"},
["wikipedia.firstpartyapps.oaspapps.com"] = {"whitelist","office365","common"},
["wordcs.officeapps.live.com"] = {"whitelist","office365","common"},
["wu.client.hip.live.com"] = {"whitelist","office365","common"},
["wus-000.forms.osi.office.net"] = {"whitelist","office365","common"},
["wus-000.tasks.osi.office.net"] = {"whitelist","office365","common"},
["wus-firstpartyapps.oaspapps.com"] = {"whitelist","office365","common"},
["wus-www.sway-cdn.com"] = {"whitelist","office365","common"},
["wus-www.sway-extensions.com"] = {"whitelist","office365","common"},
["www.acompli.com"] = {"whitelist","office365","common"},
["www.bing.com"] = {"whitelist","office365","common"},
["www.digicert.com"] = {"whitelist","office365","common"},
["www.dropbox.com"] = {"whitelist","office365","common"},
["www.evernote.com"] = {"whitelist","office365","common"},
["www.google-analytics.com"] = {"whitelist","office365","common"},
["www.googleapis.com"] = {"whitelist","office365","common"},
["www.microsoft.com"] = {"whitelist","office365","common"},
["www.office.com"] = {"whitelist","office365","common"},
["www.onedrive.com"] = {"whitelist","office365","common"},
["www.outlook.com"] = {"whitelist","office365","common"},
["www.sway.com"] = {"whitelist","office365","common"},
["www.wunderlist.com"] = {"whitelist","office365","common"},
["www.youtube.com"] = {"whitelist","office365","common"}
})

O365:setKeys({
	nwlanguagekey.create("filter", nwtypes.Text),
	nwlanguagekey.create("feed.name", nwtypes.Text),
})

function O365:onHost(idx, host)
    --lowercase the incoming value
    host = string.lower(host)
	
    for domain in pairs(lookup_list) do
   
        -- replace the * wildcard in the list with .*
        domain_esc = string.gsub(domain, "%*", "%.%*")
        --print("domain after gsub for * " .. domain)
        
        -- for hostnames that have a - in them we need to escape that with %% so the end string ends %- (first % escapes on replace)
        domain_esc = string.gsub(domain_esc, "%-", "%%-")
        
        if string.match(host, "^"..domain_esc.."$") then
            -- QUESTIONS::
            -- should the list match both specific and wildcard matches?
            -- should the list only match specific first and then do wildcard only if no match
            -- if above is correct, list should be ordered specific first then wildcard so that first match exits the loop
            
            --print(domain_esc)
            for index,list_value in ipairs(lookup_list[domain]) do
                -- this is the counter in the table
                --print(index)
                -- this is the value from the table
                --print(list_value)
                nw.createMeta(self.keys["filter"], list_value)
            end
            
            -- finally aftger writing all the values from the matched value update the  feed.name meta
            -- this throws an error oddly
            nw.createMeta(self.keys["feed.name"], parserName)
        
        end
    end
    --end
end

O365:setCallbacks({
    [nwlanguagekey.create("alias.host")] = O365.onHost,
    [nwlanguagekey.create("fqdn")] = O365.onHost,
    [nwlanguagekey.create("host.src")] = O365.onHost,
    [nwlanguagekey.create("host.dst")] = O365.onHost
})
